name: Build_NUnitTests1
on:
  push:
    branches:
      - refs/heads/main
  workflow_run:
    workflows:
      - Build_Dev
    types:
      - requested
jobs:
  runs-on: ''
  steps:
    - name: BuildStep_NUnitTests
      run: PS1
env: {}
