name: Build_NUnitTests
on:
  push:
    branches:
      - refs/heads/main
  workflow_run:
    workflows:
      - Build_Dev
    types:
      - requested
jobs:
  build:
    runs-on: ''
    steps:
    - name: BuildStep_NUnitTests
      run: PS1
env: {}

