name: Build_NUnitTests1
on:
  push:
    branches:
      - refs/heads/main
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: ubuntu-latest
    steps:
     - name: BuildStep_NUnitTests
       run: echo "test"
