name: Retry Triggered Workflow

on:
  workflow_run:
    workflows:
      - Parentworkflow
    types:
      - completed

jobs:
  retry_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check if triggering workflow failed
        id: check_triggering_workflow
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const workflowRun = context.payload.workflow_run;
            const status = workflowRun.conclusion;
            console.log(`Triggering workflow status: ${status}`);
            if (status === "failure") {
              core.setOutput('retry', 'true');
            }

      - name: Retry triggered workflow if needed
        id: retry
        if: steps.check_triggering_workflow.outputs.retry == 'true'
        run: |
          for retry_attempt in 1 2 3; do
            echo "Attempting retry $retry_attempt of the triggered workflow..."
            workflow_run_id=$(curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/Parentworkflow.yml/dispatches" \
              -d '{"ref":"main"}' | jq -r '.id')
            if [ "$workflow_run_id" != "null" ]; then
              workflow_status=$(curl -s \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/actions/runs/$workflow_run_id" | jq -r '.conclusion')
              if [ "$workflow_status" == "success" ]; then
                echo "Triggered workflow succeeded."
                break
              fi
            fi
            sleep 30
          done
