name: TestDispatchWorkflow

on:
  workflow_dispatch:
   

jobs:
  retry_job:
    runs-on: ubuntu-latest
    steps:
    
      - name: Retry triggered workflow if needed
        id: retry
     
        run: |
         
            workflow_run_id=$(curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/Parentworkflow.yml/dispatches" \
              -d '{"ref":"main"}' )
             echo "the workflow id is"
             echo {{ fromjson($workflow_run_id)}}
           
        
