name: TestGitHubActions_Build

on:
  push:
    branches: [refs/heads/main]
  pull_request:
    branches: [refs/heads/main]
  repository_dispatch:
    types: trigger-parent-workflow
  workflow_dispatch:

jobs:
   dep1: 

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    

    steps:
    - name: BuildStep_NUnitTests
      run: echo "running nUnit test workflow 1"

