name: Build_NUnitTests
on:
  push:
    branches:
      - refs/heads/main
  workflow_dispatch: {}
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: BuildStep_NUnitTests
        run: |-
          pwsh -Command ./Test.ps1
