name: Build_Dev

on:
  push:
    branches: [refs/heads/main]
  pull_request:
    branches: [refs/heads/main]
  workflow_dispatch:
  workflow_run:
    workflows: ["Build_NUnitTests"]
    types:
      - completed
  

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

   
    runs-on: ubuntu-latest

    env:
      Test_Config_Param: test_config
      test_env: test_env
      system.test_system: test_system

    steps:
    - name: Check if Triggered Workflow was successful
      id: check_trigger_status
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/:repository/actions/runs/${{ github.event.workflow.id }}
        repository: ${{ github.event.repository.full_name }}
        
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      
    
      
  
    - name: BuildStep_CommandLine
      run: |
        
        echo "in test"

    - name: BuildStep_MetaRunner
      run: |
        echo "test meta runner"
