name: TestGitHubActions_Build

on:
  push:
    branches: [refs/heads/main]
  pull_request:
    branches: [refs/heads/main]
  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    

    steps:
    - name: BuildStep_NUnitTests
      run: |

