name: Build_NUnitTests
on:
  push:
    branches:
      - refs/heads/main
  workflow_dispatch: {}
  workflow_run:
    workflows:
      - Build_Dev
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: BuildStep_NUnitTests
        run: |-
          pwsh -Command ./Test.ps1
