name: Build_NUnitTests

on:
  push:
    branches:
      - refs/heads/main
  workflow_run:
    workflows:
      - Build_Dev
    types:
      - requested

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: ubuntu-latest
    steps:
    - name: BuildStep_NUnitTests
      run: echo "running unit test"
