name: Build_Dev

on:
  push:
    branches: [refs/heads/main]
  pull_request:
    branches: [refs/heads/main]
   workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

   
    runs-on: ubuntu-latest

    env:
      Test_Config_Param: test_config
      test_env: test_env
      system.test_system: test_system

    steps:
  
    - name: BuildStep_CommandLine
      run: |
        
        echo "in test"

    - name: BuildStep_MetaRunner
      run: |
        echo "test meta runner"
